config {
  type: "table",
  schema: "trusted",
  name: "trusted_bitcoin",
  tags: ["bitcoin"]
}

WITH raw_data AS (
  SELECT prices, _metadados FROM ${ref("raw_bitcoin")}
)

SELECT
  -- O item é '[1769662279111, 457957.89]'
  -- Pega o índice 0 (Timestamp)
  TIMESTAMP_MILLIS(CAST(JSON_VALUE(item, '$[0]') AS INT64)) as data_referencia,
  
  -- Pega o índice 1 (Valor)
  CAST(JSON_VALUE(item, '$[1]') AS FLOAT64) as valor_brl,
  
  -- Metadados
  CAST(JSON_VALUE(_metadados, '$.data_ingestao') AS TIMESTAMP) as data_ingestao,
  JSON_VALUE(_metadados, '$.origem') as origem,
  
  CURRENT_TIMESTAMP() as data_processamento

FROM raw_data,
-- JSON_EXTRACT_ARRAY transforma a lista gigante em várias linhas pequenas
UNNEST(JSON_EXTRACT_ARRAY(prices)) as item